using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AHCBL.Dto.Admin
{
    public class BoardListDto
    {
        public int id { get; set; }
        public string bo_table { get; set; }
        public int grp_id { get; set; }
        public string bo_subject { get; set; }
        public string bo_mobile_subject { get; set; }
        public string bo_device { get; set; }
        public string grp_device { get; set; }
        public string all_device { get; set; }
        public string category_list { get; set; }
        public string use_category { get; set; }
        public string grp_category_list { get; set; }
        public string all_category_list { get; set; }
        public string bo_admin { get; set; }
        public string grp_admin { get; set; }
        public string all_admin { get; set; }
        public string bo_list_level { get; set; }
        public string grp_list_level { get; set; }
        public string all_list_level { get; set; }
        public string bo_read_level { get; set; }
        public string grp_read_level { get; set; }
        public string all_read_level { get; set; }
        public string bo_write_level { get; set; }
        public string grp_write_level { get; set; }
        public string all_write_level { get; set; }
        public string reply_level { get; set; }
        public string grp_reply_level { get; set; }
        public string all_reply_level { get; set; }
        public string comment_level { get; set; }
        public string grp_comment_level { get; set; }
        public string all_comment_level { get; set; }
        public string link_level { get; set; }
        public string grp_link_level { get; set; }
        public string all_link_level { get; set; }
        public string upload_level { get; set; }
        public string grp_upload_level { get; set; }
        public string all_upload_level { get; set; }
        public string download_level { get; set; }
        public string grp_download_level { get; set; }
        public string all_download_level { get; set; }
        public string html_level { get; set; }
        public string grp_html_level { get; set; }
        public string all_html_level { get; set; }
        public string count_modify { get; set; }
        public string grp_count_modify { get; set; }
        public string all_count_modify { get; set; }
        public string count_delete { get; set; }
        public string grp_count_delete { get; set; }
        public string all_count_delete { get; set; }
        public string use_sideview { get; set; }
        public string grp_use_sideview { get; set; }
        public string all_use_sideview { get; set; }
        public string use_secret { get; set; }
        public string grp_use_secret { get; set; }
        public string all_use_secret { get; set; }
        public string use_dhtml_editor { get; set; }
        public string grp_use_dhtml_editor { get; set; }
        public string all_use_dhtml_editor { get; set; }
        public string use_rss_view { get; set; }
        public string grp_use_rss_view { get; set; }
        public string all_use_rss_view { get; set; }
        public string use_good { get; set; }
        public string grp_use_good { get; set; }
        public string all_use_good { get; set; }
        public string use_nogood { get; set; }
        public string grp_use_nogood { get; set; }
        public string use_name { get; set; }
        public string grp_use_name { get; set; }
        public string all_use_name { get; set; }
        public string use_signature { get; set; }
        public string grp_use_signature { get; set; }
        public string all_use_signature { get; set; }
        public string use_ip_view { get; set; }
        public string grp_use_ip_view { get; set; }
        public string all_use_ip_view { get; set; }
        public string use_list_content { get; set; }
        public string grp_use_list_content { get; set; }
        public string all_use_list_content { get; set; }
        public string use_list_file { get; set; }
        public string grp_use_list_file { get; set; }
        public string all_use_list_file { get; set; }
        public string use_list_view { get; set; }
        public string grp_use_list_view { get; set; }
        public string all_use_list_view { get; set; }
        public string use_email { get; set; }
        public string grp_use_email { get; set; }
        public string all_use_email { get; set; }
        public string use_cert { get; set; }
        public string grp_use_cert { get; set; }
        public string all_use_cert { get; set; }
        public string upload_count { get; set; }
        public string grp_upload_count { get; set; }
        public string all_upload_count { get; set; }
        public string upload_size { get; set; }
        public string grp_upload_size { get; set; }
        public string all_upload_size { get; set; }
        public string use_file_content { get; set; }
        public string grp_use_file_content { get; set; }
        public string all_use_file_content { get; set; }
        public string write_min { get; set; }
        public string grp_write_min { get; set; }
        public string all_write_min { get; set; }
        public string write_max { get; set; }
        public string grp_write_max { get; set; }
        public string all_write_max { get; set; }
        public string comment_min { get; set; }
        public string grp_comment_min { get; set; }
        public string all_comment_min { get; set; }
        public string comment_max { get; set; }
        public string grp_comment_max { get; set; }
        public string all_comment_max { get; set; }
        public string use_sns { get; set; }
        public string grp_use_sns { get; set; }
        public string all_use_sns { get; set; }
        public string use_search { get; set; }
        public string grp_use_search { get; set; }
        public string all_use_search { get; set; }
        public string bo_order { get; set; }
        public string grp_order { get; set; }
        public string all_order { get; set; }
        public string use_captcha { get; set; }
        public string grp_use_captcha { get; set; }
        public string all_use_captcha { get; set; }
        public int skin_id { get; set; }
        public string grp_skin { get; set; }
        public string all_skin { get; set; }
        public int skin_mobile_id { get; set; }
        public string grp_mobile_skin { get; set; }
        public string all_mobile_skin { get; set; }
        public string include_head { get; set; }
        public string grp_include_head { get; set; }
        public string all_include_head { get; set; }
        public string include_tail { get; set; }
        public string grp_include_tail { get; set; }
        public string all_include_tail { get; set; }
        public string detail_hots { get; set; }
        public string grp_detail_hots { get; set; }
        public string all_detail_hots { get; set; }
        public string detail_tail { get; set; }
        public string grp_detail_tail { get; set; }
        public string all_detail_tail { get; set; }
        public string detail_mobile_hots { get; set; }
        public string grp_detail_mobile_hots { get; set; }
        public string all_detail_mobile_hots { get; set; }
        public string detail_mobile_tail { get; set; }
        public string grp_detail_mobile_tail { get; set; }
        public string all_detail_mobile_tail { get; set; }
        public string insert_content { get; set; }
        public string grp_insert_content { get; set; }
        public string all_insert_content { get; set; }
        public string subject_len { get; set; }
        public string grp_subject_len { get; set; }
        public string all_subject_len { get; set; }
        public string mobile_subject_len { get; set; }
        public string grp_mobile_subject_len { get; set; }
        public string all_mobile_subject_len { get; set; }
        public string page_rows { get; set; }
        public string grp_page_rows { get; set; }
        public string all_page_rows { get; set; }
        public string mobile_page_rows { get; set; }
        public string grp_mobile_page_rows { get; set; }
        public string all_mobile_page_rows { get; set; }
        public string gallery_cols { get; set; }
        public string grp_gallery_cols { get; set; }
        public string all_gallery_cols { get; set; }
        public string gallery_width { get; set; }
        public string grp_gallery_width { get; set; }
        public string all_gallery_width { get; set; }
        public string gallery_height { get; set; }
        public string grp_gallery_height { get; set; }
        public string all_gallery_height { get; set; }
        public string mobile_gallery_width { get; set; }
        public string grp_mobile_gallery_width { get; set; }
        public string all_mobile_gallery_width { get; set; }
        public string mobile_gallery_height { get; set; }
        public string grp_mobile_gallery_height { get; set; }
        public string all_mobile_gallery_height { get; set; }
        public string table_width { get; set; }
        public string grp_table_width { get; set; }
        public string all_table_width { get; set; }
        public string image_width { get; set; }
        public string grp_image_width { get; set; }
        public string all_image_width { get; set; }
        public string icon_new { get; set; }
        public string grp_icon_new { get; set; }
        public string all_icon_new { get; set; }
        public string icon_hot { get; set; }
        public string grp_icon_hot { get; set; }
        public string all_icon_hot { get; set; }
        public string reply_order { get; set; }
        public string grp_reply_order { get; set; }
        public string all_reply_order { get; set; }
        public int sort_field { get; set; }
        public string grp_sort_field { get; set; }
        public string all_sort_field { get; set; }
        public string grp_point { get; set; }
        public string read_point { get; set; }
        public string write_point { get; set; }
        public string comment_point { get; set; }
        public string download_point { get; set; }
        public string subj1 { get; set; }
        public string txt1 { get; set; }
        public int grp_1 { get; set; }
        public int all_1 { get; set; }
        public string subj2 { get; set; }
        public string txt2 { get; set; }
        public int grp_2 { get; set; }
        public int all_2 { get; set; }
        public string subj3 { get; set; }
        public string txt3 { get; set; }
        public int grp_3 { get; set; }
        public int all_3 { get; set; }
        public string subj4 { get; set; }
        public string txt4 { get; set; }
        public int grp_4 { get; set; }
        public int all_4 { get; set; }
        public string subj5 { get; set; }
        public string txt5 { get; set; }
        public int grp_5 { get; set; }
        public int all_5 { get; set; }
        public string subj6 { get; set; }
        public string txt6 { get; set; }
        public int grp_6 { get; set; }
        public int all_6 { get; set; }
        public string subj7 { get; set; }
        public string txt7 { get; set; }
        public int grp_7 { get; set; }
        public int all_7 { get; set; }
        public string subj8 { get; set; }
        public string txt8 { get; set; }
        public int grp_8 { get; set; }
        public int all_8 { get; set; }
        public string subj9 { get; set; }
        public string txt9 { get; set; }
        public int grp_9 { get; set; }
        public int all_9 { get; set; }
        public string subj10 { get; set; }
        public string txt10 { get; set; }
        public int grp_10 { get; set; }
        public int all_10 { get; set; }


    }
}
